### PR TITLE
Upgrade to Laravel 10

### PR DESCRIPTION
**Pull request by alexanderkroneis**

### CODE REVIEW

**Comment by JustSteveKing** [comment]
@mpociot or @sschlein  or @mechelon feel free to schedule a release of this version when you are ready!

**Comment by alexanderkroneis** [comment]
@mpociot Do you know when you‘ll release a new version? 👀

**Comment by JustSteveKing** [comment]
I didn't hear anything back - so have released this myself @alexgaal

**Comment by mechelon** [comment]
This drops support for Laravel 9 projects, doesn't it?

**Comment by alexanderkroneis** [comment]
> This drops support for Laravel 9 projects, doesn't it?
@mechelon 

Yes, it does indeed drop Laravel 9 support.

**Pull request merged**
